include ~/.config/kitty/themes/gruvbox_dark.conf
font_family      family='JetBrainsMono Nerd Font' style=Medium
bold_font        family='JetBrainsMono Nerd Font' style=Bold
italic_font      family='JetBrainsMono Nerd Font' style='Medium Italic'
bold_italic_font family='JetBrainsMono Nerd Font' style='Bold Italic'

font_size 18

allow_remote_control yes
enable_audio_bell no
enable_link_hints yes

shell_integration  no-cursor
cursor_shape block
cursor_blink_interval 0

hide_window_decorations yes

touch_scroll_multiplier 10.0

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

background_opacity 1.0
window_padding_width 4

