format = """
[](fg:color_orange)\
$username\
[](fg:color_orange bg:color_yellow)\
$directory\
[](fg:color_yellow bg:color_blue)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:color_blue bg:color_bg2)\
$cmd_duration\
[ ](fg:color_bg2)\
$c\
$nodejs\
$java\
$python\
$dotnet\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg1 = '#ebdbb2'
color_fg2 = '#d5c4a1'
color_bg1 = '#3c3836'
color_bg2 = '#504945'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#d3869b'
color_red = '#cc241d'
color_yellow = '#d79921'

[username]
show_always = true
format = '[󰣛 $user](bg:color_orange fg:color_fg1)'

[directory]
read_only = '󰌾 '
format = "[ $read_only$path](fg:color_fg1 bg:color_yellow)"
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
truncation_length = 8
truncation_symbol = '…'
format = '[  $branch](fg:color_fg1 bg:color_blue)'
only_attached = false
disabled = false

[git_commit]
commit_hash_length = 7
format = '[  $hash](fg:color_fg1 bg:color_blue)'
only_detached = true
tag_disabled = true
disabled = false

[git_state]
rebase = ' '
merge = ''
revert = ' '
cherry_pick = '󱁂 '
bisect = ' '
am = ' '
am_or_rebase = ' / '
format = '[$state](fg:color_fg1 bg:color_blue)'
disabled = false

[git_status]
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = '[$all_status$ahead_behind](fg:color_fg1 bg:color_blue)'

[nodejs]
format = '[  $version](fg:color_fg2)'

[c]
format = '[  $name $version](fg:color_fg2)'

[java]
format = '[  $version](fg:color_fg2)'

[python]
format = '[  $version(\($virtualenv\))](fg:color_fg2)'

[dotnet]
format = '[ 󰪮 $version](fg:color_fg2)'

# [docker_context]
# format = '[  ($context)](fg:color_fg1 bg:color_bg2)'

[cmd_duration]
min_time = 1000
format = '[  $duration](fg:color_fg1 bg:color_bg2)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '\$'
error_symbol = '\$'
