add_newline = false

format = """
$python\
$character\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status """


[python]
format = '(\([󰌠 ](bright-white)[$virtualenv](bright-yellow)\))'


[character]
success_symbol = '[ ➜](bright-white)'
error_symbol = '[ ➜](bright-white)'


[directory]
truncation_length = 1
read_only = '󱈸'
read_only_style = 'bright-red'
format = '[$path](bright-green)[$read_only]($read_only_style)'


[git_branch]
truncation_length = 8
truncation_symbol = '…'
format = '\([ ](bright-white)[$branch](bright-blue)'


[git_commit]
commit_hash_length = 7
format = '\([ ](bright-white)[$hash](bright-blue)'
only_detached = true
tag_disabled = true


[git_state]
rebase = ' '
merge = ''
revert = ' '
cherry_pick = '󱁂 '
bisect = ' '
am = ' '
am_or_rebase = ' / '
format = '[$state](bright-purple)'


[git_status]
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = '[$all_status$ahead_behind](bright-purple)\)'
