add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$c\
$java\
$python\
$nodejs\
$dotnet\
$fill\
$cmd_duration\
$line_break\
$character\
"""


palette = 'gruvbox'

[palettes.gruvbox]
fg3 = '#bdae93'
bg0_s = '#32302f'
bg1 = '#3c3836'
blue = '#83a598'
aqua = '#8ec07c'
green = '#b8bb26'
orange = '#fe8019'
purple = '#d3869b'
red = '#cc241d'
yellow = '#fabd2f'


[username]
format = """
[](green)\
[󰣛 ](fg:bg0_s bg:green)\
[ $user](fg:green bg:bg1)\
[$read_only]($read_only_style)\
[](bg1) \
"""
disabled = false
show_always = true


[directory]
truncation_length = 1
read_only = '󱈸'
read_only_style = 'fg:orange bg:bg1'
format = """
[](aqua)\
[ ](fg:bg0_s bg:aqua)\
[ $path](fg:aqua bg:bg1)\
[$read_only]($read_only_style)\
[](bg1) \
"""
disabled = false
use_os_path_sep = false
truncate_to_repo = false


[git_branch]
truncation_length = 8
truncation_symbol = '…'
format = """
[](blue)\
[ ](fg:bg0_s bg:blue)\
[ $branch](fg:blue bg:bg1)\
"""
only_attached = false
disabled = false


[git_commit]
commit_hash_length = 7
format = """
[](blue)\
[ ](fg:bg0_s bg:blue)\
[ $hash](fg:blue bg:bg1)\
"""
only_detached = true
tag_disabled = true
disabled = false


[git_state]
rebase = ' '
merge = ''
revert = ' '
cherry_pick = '󱁂 '
bisect = ' '
am = ' '
am_or_rebase = ' / '
format = '[$state](fg:orange bg:bg1)'
disabled = false


[git_status]
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = """
[$all_status$ahead_behind](fg:purple bg:bg1)\
[](bg1) \
"""


[c]
detect_extensions = ['c', 'cpp', 'h', 'hpp']
format = '[ $name $version](fg3) '


[java]
format = '[ $version](fg3) '


[python]
format = '[󰌠 $version (\($virtualenv\))](fg3) '


[nodejs]
format = '[ $version](fg3) '


[dotnet]
format = '[󰪮 $version](fg3) '


[fill]
symbol = ' '


[cmd_duration]
min_time = 1000
format = """
[](yellow)\
[ ](fg:bg0_s bg:yellow)\
[ $duration](fg:yellow bg:bg1)\
[](bg1) \
"""
 

[character]
success_symbol = '[](#bdae93)'
error_symbol = '[](#bdae93)'
