add_newline = false

format = """
$python\
$character\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status """


[python]
format = '(\([󰌠 ](#bdae93)[$virtualenv](#fabd2f)\))'


[character]
success_symbol = '[ ➜](#bdae93)'
error_symbol = '[ ➜](#bdae93)'


[directory]
truncation_length = 1
read_only = '󱈸'
read_only_style = '#fe8019'
format = '[$path](fg:#b8bb26)[$read_only]($read_only_style)'


[git_branch]
truncation_length = 8
truncation_symbol = '…'
format = '\([ ](#bdae93)[$branch](#83a598)'


[git_commit]
commit_hash_length = 7
format = '\([ ](#bdae93)[$hash](#83a598)'
only_detached = true
tag_disabled = true


[git_state]
rebase = ' '
merge = ''
revert = ' '
cherry_pick = '󱁂 '
bisect = ' '
am = ' '
am_or_rebase = ' / '
format = '[$state](#fe8019)'


[git_status]
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = '[$all_status$ahead_behind](#d3869b)\)'
