add_newline = false

format = """
[](fg:user_color)\
$username\
[](fg:user_color bg:path_color)\
$directory\
$python\
[](fg:path_color bg:git_color)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:git_color bg:bg_color)\
$cmd_duration\
[](fg:bg_color)\
$line_break$character"""

palette = 'gruvbox_purple'

[palettes.gruvbox_orange]
fg_color = '#ebdbb2'
bg_color = '#504945'
user_color = '#cc241d'
path_color = '#d65d0e'
git_color = '#d79921'

[palettes.gruvbox_purple]
fg_color = '#ebdbb2'
bg_color = '#504945'
user_color = '#b16286'
path_color = '#458588'
git_color = '#689d6a'

[username]
show_always = true
format = '[󰣛 $user](bg:user_color fg:fg_color)'

[directory]
read_only = '󰌾 '
format = "[ $read_only$path](fg:fg_color bg:path_color)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
truncation_length = 8
truncation_symbol = '…'
format = '[  $branch](fg:fg_color bg:git_color)'
only_attached = false
disabled = false

[git_commit]
commit_hash_length = 7
format = '[  $hash](fg:fg_color bg:git_color)'
only_detached = true
tag_disabled = true
disabled = false

[git_state]
rebase = ' '
merge = ''
revert = ' '
cherry_pick = '󱁂 '
bisect = ' '
am = ' '
am_or_rebase = ' / '
format = '[$state](fg:fg_color bg:git_color)'
disabled = false

[git_status]
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = '[$all_status$ahead_behind](fg:fg_color bg:git_color)'

[python]
format = '[(\($virtualenv\))](fg:fg_color bg:path_color)'

[cmd_duration]
min_time = 1000
format = '[  $duration](fg:fg_color bg:bg_color)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '\$'
error_symbol = '\$'
