format = """
[](fg:orange)\
$username\
[](fg:orange bg:yellow)\
$directory\
[](fg:yellow bg:blue)\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](fg:blue bg:bg2)\
$cmd_duration\
[ ](fg:bg2)\
$c\
$nodejs\
$java\
$python\
$dotnet\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
fg1 = '#ebdbb2'
fg2 = '#d5c4a1'
bg1 = '#3c3836'
bg2 = '#504945'
blue = '#458588'
aqua = '#689d6a'
green = '#98971a'
orange = '#d65d0e'
purple = '#b16286'
red = '#cc241d'
yellow = '#d79921'

[username]
show_always = true
format = '[󰣛 $user](bg:orange fg:fg1)'

[directory]
read_only = '󰌾 '
format = "[ $read_only$path](fg:fg1 bg:yellow)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
truncation_length = 8
truncation_symbol = '…'
format = '[  $branch](fg:fg1 bg:blue)'
only_attached = false
disabled = false

[git_commit]
commit_hash_length = 7
format = '[  $hash](fg:fg1 bg:blue)'
only_detached = true
tag_disabled = true
disabled = false

[git_state]
rebase = ' '
merge = ''
revert = ' '
cherry_pick = '󱁂 '
bisect = ' '
am = ' '
am_or_rebase = ' / '
format = '[$state](fg:fg1 bg:blue)'
disabled = false

[git_status]
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = '[$all_status$ahead_behind](fg:fg1 bg:blue)'

[nodejs]
format = '[  $version](fg:fg2)'

[c]
format = '[  $name $version](fg:fg2)'

[java]
format = '[  $version](fg:fg2)'

[python]
format = '[  $version(\($virtualenv\))](fg:fg2)'

[dotnet]
format = '[ 󰪮 $version](fg:fg2)'

# [docker_context]
# format = '[  ($context)](fg:fg1 bg:bg2)'

[cmd_duration]
min_time = 1000
format = '[  $duration](fg:fg1 bg:bg2)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '\$'
error_symbol = '\$'
